export const countryToZone: Record<string, string> = {
    "Afghanistan": "Asia/Kabul", "Albania": "Europe/Tirane", "Algeria": "Africa/Algiers", "Andorra": "Europe/Andorra",
    "Angola": "Africa/Luanda", "Argentina": "America/Argentina/Buenos_Aires", "Armenia": "Asia/Yerevan", 
    "Australia": "Australia/Sydney", "Austria": "Europe/Vienna", "Azerbaijan": "Asia/Baku", "Bahamas": "America/Nassau",
    "Bahrain": "Asia/Bahrain", "Bangladesh": "Asia/Dhaka", "Barbados": "America/Barbados", "Belarus": "Europe/Minsk",
    "Belgium": "Europe/Brussels", "Belize": "America/Belize", "Benin": "Africa/Porto-Novo", "Bhutan": "Asia/Thimphu",
    "Bolivia": "America/La_Paz", "Brazil": "America/Sao_Paulo", "Brunei": "Asia/Brunei", "Bulgaria": "Europe/Sofia",
    "Burkina Faso": "Africa/Ouagadougou", "Burundi": "Africa/Bujumbura", "Cambodia": "Asia/Phnom_Penh", "Cameroon": "Africa/Douala",
    "Canada": "America/Toronto", "Chad": "Africa/Ndjamena", "Chile": "America/Santiago", "China": "Asia/Shanghai",
    "Colombia": "America/Bogota", "Congo": "Africa/Brazzaville", "Costa Rica": "America/Costa_Rica", "Croatia": "Europe/Zagreb",
    "Cuba": "America/Havana", "Cyprus": "Asia/Nicosia", "Czech Republic": "Europe/Prague", "Denmark": "Europe/Copenhagen",
    "Djibouti": "Africa/Djibouti", "Dominica": "America/Dominica", "Ecuador": "America/Guayaquil", "Egypt": "Africa/Cairo",
    "El Salvador": "America/El_Salvador", "Estonia": "Europe/Tallinn", "Ethiopia": "Africa/Addis_Ababa", "Fiji": "Pacific/Fiji",
    "Finland": "Europe/Helsinki", "France": "Europe/Paris", "Gabon": "Africa/Libreville", "Gambia": "Africa/Banjul",
    "Georgia": "Asia/Tbilisi", "Germany": "Europe/Berlin", "Ghana": "Africa/Accra", "Greece": "Europe/Athens",
    "Guatemala": "America/Guatemala", "Guinea": "Africa/Conakry", "Guyana": "America/Guyana", "Haiti": "America/Port-au-Prince",
    "Honduras": "America/Tegucigalpa", "Hungary": "Europe/Budapest", "Iceland": "Atlantic/Reykjavik", "India": "Asia/Kolkata",
    "Indonesia": "Asia/Jakarta", "Iran": "Asia/Tehran", "Iraq": "Asia/Baghdad", "Ireland": "Europe/Dublin",
    "Israel": "Asia/Jerusalem", "Italy": "Europe/Rome", "Jamaica": "America/Jamaica", "Japan": "Asia/Tokyo",
    "Jordan": "Asia/Amman", "Kazakhstan": "Asia/Almaty", "Kenya": "Africa/Nairobi", "Kuwait": "Asia/Kuwait",
    "Kyrgyzstan": "Asia/Bishkek", "Laos": "Asia/Vientiane", "Latvia": "Europe/Riga", "Lebanon": "Asia/Beirut",
    "Libya": "Africa/Tripoli", "Lithuania": "Europe/Vilnius", "Luxembourg": "Europe/Luxembourg", "Madagascar": "Africa/Antananarivo",
    "Malaysia": "Asia/Kuala_Lumpur", "Maldives": "Asia/Male", "Mali": "Africa/Bamako", "Malta": "Europe/Malta",
    "Mauritania": "Africa/Nouakchott", "Mauritius": "Indian/Mauritius", "Mexico": "America/Mexico_City", "Monaco": "Europe/Monaco",
    "Mongolia": "Asia/Ulaanbaatar", "Montenegro": "Europe/Podgorica", "Morocco": "Africa/Casablanca", "Mozambique": "Africa/Maputo",
    "Myanmar": "Asia/Yangon", "Namibia": "Africa/Windhoek", "Nepal": "Asia/Kathmandu", "Netherlands": "Europe/Amsterdam",
    "New Zealand": "Pacific/Auckland", "Nicaragua": "America/Managua", "Niger": "Africa/Niamey", "Nigeria": "Africa/Lagos",
    "North Korea": "Asia/Pyongyang", "Norway": "Europe/Oslo", "Oman": "Asia/Muscat", "Pakistan": "Asia/Karachi",
    "Panama": "America/Panama", "Paraguay": "America/Asuncion", "Peru": "America/Lima", "Philippines": "Asia/Manila",
    "Poland": "Europe/Warsaw", "Portugal": "Europe/Lisbon", "Qatar": "Asia/Qatar", "Romania": "Europe/Bucharest",
    "Russia": "Europe/Moscow", "Rwanda": "Africa/Kigali", "Saudi Arabia": "Asia/Riyadh", "Senegal": "Africa/Dakar",
    "Serbia": "Europe/Belgrade", "Singapore": "Asia/Singapore", "Slovakia": "Europe/Bratislava", "Slovenia": "Europe/Ljubljana",
    "South Africa": "Africa/Johannesburg", "South Korea": "Asia/Seoul", "Spain": "Europe/Madrid", "Sri Lanka": "Asia/Colombo",
    "Sudan": "Africa/Khartoum", "Sweden": "Europe/Stockholm", "Switzerland": "Europe/Zurich", "Syria": "Asia/Damascus",
    "Taiwan": "Asia/Taipei", "Tajikistan": "Asia/Dushanbe", "Tanzania": "Africa/Dar_es_Salaam", "Thailand": "Asia/Bangkok",
    "Tunisia": "Africa/Tunis", "Turkey": "Europe/Istanbul", "Turkmenistan": "Asia/Ashgabat", "Uganda": "Africa/Kampala",
    "Ukraine": "Europe/Kyiv", "UAE": "Asia/Dubai", "United Kingdom": "Europe/London", "USA": "America/New_York",
    "Uruguay": "America/Montevideo", "Uzbekistan": "Asia/Tashkent", "Venezuela": "America/Caracas", "Vietnam": "Asia/Ho_Chi_Minh",
    "Yemen": "Asia/Aden", "Zambia": "Africa/Lusaka", "Zimbabwe": "Africa/Harare"
};
